using UnityEngine;

public class VentiladorScript : MonoBehaviour
{
    // Par치metros configurables
    public Vector2 direccion = Vector2.right;  // Direcci칩n de la fuerza del ventilador
    public float fuerza = 5f;                  // Fuerza que aplicar치 el ventilador

    private void OnTriggerStay2D(Collider2D other)
    {
        // Verifica si el objeto que entra es la pelota
        if (other.gameObject.name == "Ball")
        {
            // Obtiene el Rigidbody2D de la pelota
            Rigidbody2D rb = other.GetComponent<Rigidbody2D>();

            if (rb != null)
            {
                // Aplica una fuerza continua en la direcci칩n especificada
                rb.AddForce(direccion.normalized * fuerza);
            }
        }
    }
}
